### ISSUE TITLE
Extensions are removed by default

### ISSUE THREAD

**Issue by mrexox** [lfittl/activerecord-clean-db-structure#21]
Maybe you should add a property to allow removal or keeping the extensions? I faced the problem where it would be very useful. For instance:

```
config.activerecord_clean_db_structure.ignore_extensions = true
```

or

```
config.activerecord_clean_db_structure.remove_extensions = false
```

**Comment by andyatkinson** [comment]
@mrexox Hi there. It's been nearly 5 years since you posted this issue, but it's getting some traction! I'm wondering if this is still a gem you use and whether you'd like to weigh in on what's being discussed:
https://github.com/lfittl/activerecord-clean-db-structure/issues/42#issuecomment-2321758837

Also, would you like to work on an implementation of adding this new setting depending on the output of that discussion? Thanks.

**Comment by mrexox** [comment]
Hey, @andyatkinson! Thank you for a mention. It's been a while and right now I don't use the gem and can't remember the original issues I faced when I was creating the issue, unfortunately. It's my bad – I've lost the context 😕 I guess you can close the issue in this case.

**Comment by andyatkinson** [comment]
Hi @mrexox Thanks, no problem. That linked issue is discussing a few possible implementations. I think this implementation of a boolean that excludes all extensions, is probably the best place to start. 

Since you're not using this, I wouldn't expect you contribute an implementation. However, the next step would be that we'd need an implementation of this new setting, including the code and some documentation of how it works in the change log at a minimum.
