### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by walski** [lfittl/activerecord-clean-db-structure#33]
Hey @lfittl can you cut a new gem that includes 875e64b? Would be much appreciated.

Thank you!!

Thorben

**Comment by Bertg** [comment]
Yeah, a release would be nice

**Comment by zacheryph** [comment]
3rd this

**Comment by srpouyet** [comment]
4th this!

**Comment by nzifnab** [comment]
Any update on this...?

**Comment by andrewmusk** [comment]
5th on this

**Comment by andyatkinson** [comment]
This gem was mentioned in the most recent postgres.fm episode. https://postgres.fm/episodes/rails-postgres 😄

**Comment by huda-kh** [comment]
Is this gem no longer being maintained?

**Comment by Bertg** [comment]
I think at this point a fork might been order. The current licence allows for it.

**Comment by hlascelles** [comment]
Let's give it one more go...

@giovannibonetti @nvanoorschot @RKushnir Do any of you have rights to this? Can you merge and create a release, and if not, coordinate (with @lfittl if you know them) to assign a new maintainer?

Thanks!

**Comment by giovannibonetti** [comment]
I don't have rights to do that, sorry. I agree that a fork is the best option.

**Comment by andyatkinson** [comment]
I wrote about adopting db/structure.sql in my book and have experienced the problems this gem looks to solve. I'd love to help as a maintainer. I've worked on teams of Rails devs using the SQL structure dump, and getting "noise" diffs due to the differences in Postgres versions re-ordering things. I like how this gem solves that problem. Beyond the use as a third party gem, I think the behavior provided could even be considered for the future as future default behavior for the SQL dump format when Postgres is used.

I made a PR using the book Rails app here showing the output. This is currently for Rails 7.1 and using Postgres 16:
https://github.com/andyatkinson/rideshare/pull/175

I offered to @lfittl to be a maintainer of this gem. I'd be happy to do so. To do that, I'd need to get access to commit to this repo, and then access to the Rubygems project in order to publish new gem versions.

If a fork is created that gathers steam as an official fork, I can shift my focus there as well.

**Comment by giovannibonetti** [comment]
> I offered to @lfittl to be a maintainer of this gem. I'd be happy to do so. To do that, I'd need to get access to commit to this repo, and then access to the Rubygems project in order to publish new gem versions.

In case he is out of reach, picking out a new name is also a practical way to solve this.

**Comment by lfittl** [comment]
> I offered to @lfittl to be a maintainer of this gem. I'd be happy to do so. To do that, I'd need to get access to commit to this repo, and then access to the Rubygems project in order to publish new gem versions.

Thank you @andyatkinson!

I also want to note thanks to everyone else for the interest in helping maintain this, and in seeing new releases. Time has certainly been scarce on my end to spend on this gem at the moment, and I appreciate the help.

I've granted Andy contributor access to this repository, as well as co-ownership on Rubygems. For context, I know Andy in person as well, and I trust him with the responsibility.

For everyone else interested in helping out, please raise PRs/issues as they make sense, and Andy or myself can maintain the code and releases going forward.

**Comment by andyatkinson** [comment]
Thanks @lfittl. Confirming I now have access on Rubygems, and I've set up MFA.

I made a new PR (on my own fork) and reviewed the past versions in the changelog, and what's changed. I felt 0.4.1 might be the next best version number. 0.4.1 primarily includes the Rails 6.1+ compatibility fix, and then the other dependency updates done since 2019.

The changes are summarized in a new Changelog entry.

If you or any others could take a look and review, and after we address any comments, I'll merge it to `master` and publish the new gem version to Rubygems.

Tagging the earlier commenters: @giovannibonetti @hlascelles @Bertg @andrewmusk @nzifnab @srpouyet @zacheryph @walski 

https://github.com/lfittl/activerecord-clean-db-structure/pull/41

**Comment by andyatkinson** [comment]
@giovannibonetti @hlascelles @Bertg @andrewmusk @nzifnab @srpouyet @zacheryph @walski v0.4.1 has been published to Rubygems. Can you confirm that you're able to fetch this version in your Rails (6.1+) apps and that it has the desired additions?

Thanks!
https://rubygems.org/gems/activerecord-clean-db-structure/versions/0.4.1

**Comment by huda-kh** [comment]
I can confirm this is all good now. Thanks a lot.

**Comment by Bertg** [comment]
🚀 Nice! Thank you @andyatkinson @lfittl! And @hlascelles for the callout!
