### ISSUE TITLE
Issues with pganalyze

### ISSUE THREAD

**Issue by ghiculescu** [lfittl/activerecord-clean-db-structure#42]
I am experimenting with this gem on our repo. The database we are dumping `structure.sql` from is a structure clone of our production database, which has pganalyze installed.

So before this gem, our `structure.sql` file had

```
--
-- Name: pg_buffercache; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_buffercache WITH SCHEMA public;


--
-- Name: EXTENSION pg_buffercache; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pg_buffercache IS 'examine the shared buffer cache';
```

and

```
--
-- Name: get_buffercache(); Type: FUNCTION; Schema: pganalyze; Owner: -
--

CREATE FUNCTION pganalyze.get_buffercache() RETURNS SETOF public.pg_buffercache
    LANGUAGE sql SECURITY DEFINER
    AS $$
  /* pganalyze-collector */ SELECT * FROM public.pg_buffercache;
$$;
```

This gem [removes the extension](https://github.com/lfittl/activerecord-clean-db-structure/blob/de75f003fda2ca5a635aa2dd2d57f9661f404c64/lib/activerecord-clean-db-structure/clean_dump.rb#L28-L30). As a result, the function definition fails when trying to create a DB from the generated `structure.sql` in CI:

```
psql:/home/circleci/repo/db/structure.sql:1717: ERROR:  type "public.pg_buffercache" does not exist
```

Is there a recommended approach for setting this up if you have functions that depend on `pg_buffercache`?

**Comment by lfittl** [comment]
> Is there a recommended approach for setting this up if you have functions that depend on `pg_buffercache`?

I think that's unfortunately a limitation of how the gem currently works, which is essentially a set of regular expressions, that doesn't understand function dependencies.

Three ideas how this could be addressed:

1. I've been thinking for a while that it'd be better to utilize pg_query in this gem (https://github.com/pganalyze/pg_query) instead of regexps. That way we could parse the structure, and then be smarter about which parts to normalize/throw away -- that could include descending into function definitions, and checking for any references to extensions that got removed (though one part that's tricky with that is that an extension can create objects that are completely unrelated in terms of naming, meaning the raw parsing with pg_query wouldn't be enough to make the connection)

2. Running the structure import with `SET check_function_bodies = off`, so that unknown objects referenced in function definitions don't cause a problem (they'd only error out if the functions are actually called)

3. Allowing customization of which functions (or extensions?) get dropped, so you can configure the gem to avoid this situation

Personally I've run into this, and I've just manually modified the structure to not include the problematic function -- but that's not a great experience (since one of the main motivations for this gem is that different team members can do a DB dump and get the exact same `structure.sql` locally).

**Comment by ghiculescu** [comment]
It's not perfect, but https://github.com/lfittl/activerecord-clean-db-structure/issues/21 would also solve the immediate issue for us. Would you accept a PR for that?

**Comment by lfittl** [comment]
Yep, seems reasonable to solve it that way - /cc @andyatkinson as new co-maintainer, any thoughts?

**Comment by andyatkinson** [comment]
@lfittl With PgAnalyze in the title, I thought this might catch your attention! 😉 

I thought about https://github.com/lfittl/activerecord-clean-db-structure/issues/21 as well. I don't know the back story behind this decision, but I was surprised to see extensions removed from the source dump.

My guess as to the rationale was to keep the dump as minimal as possible, and that developers in local development, or lower environments like CI, aren't using these extensions.

Given the current design, I think among the two boolean options `config.activerecord_clean_db_structure.remove_extensions = false` would be the most consistent with the current behavior, where they're still removed by default, but optionally can all be kept.

@lfittl Was going to comment on 1,2,3 above.

1. I didn't know anything about pg_query parsing a structure dump, but that sounds very interesting! However, if you already know of a limitation for this option here, then maybe that path still needs some more investigation to possibly replace regexes in the future.

2. Cool idea. That also seems to have the problem of a not being a "complete" solution though based on what you've said, and seems like while the schema could be loaded, there's the possibility of a runtime error later on if the function were to be called. If you have examples of objects created by an extension that aren't obviously connected, that could be worth capturing for possible future use.

3. This seems like a viable alternative to a new boolean setting, except the value right hand side portion could be a comma-separated list of extension names. E.g. `keep_extensions = 'pg_buffercache,pg_stat_statements'`. This would mean that the target Postgres database would need to have these extensions available. But theoretically that would help someone opt in to specific extensions by naming them, then making sure they're available on the target instances.

I like the boolean one for simplicity, but the list one for more flexibility.

Maybe we start with the boolean one for now? @ghiculescu on your CI server you've got pg_buffercache and pg_stat_statements configured with your CI Postgres instance?

**Comment by ghiculescu** [comment]
> @ghiculescu on your CI server you've got pg_buffercache and pg_stat_statements configured with your CI Postgres instance?

We use CircleCI. For each CI run, we generate a database from the committed `structure.sql` file. The `structure.sql` file is generated based on a schema dump from our production database, combined with any changes made by the developer in the PR being tested.

So because we have `pg_buffercache` and `pg_stat_statements` on production, they end up in `structure.sql`, and so they end up in CI. But we aren't interacting with them directly in CI (or anywhere else in our codebase).

ps. I just realised who @lfittl is. Love your work!

**Comment by andyatkinson** [comment]
Hi @ghiculescu Since you don't need those extensions in CI or in local development, then it sounds like a simple boolean approach that excludes all extensions from the production dump, would work best for you.

The next step on that would be we'd need an implementation for the new setting, and some documentation in the change log and possibly elsewhere.

I mentioned that here too:
https://github.com/lfittl/activerecord-clean-db-structure/issues/21#issuecomment-2332369278

If that's something you'd like to help out on, feel free. I may be able to work on it, but so far I'm playing more of a coordinator role I guess, with my available time.

Thanks!
